name: CI

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build & Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history required for changelog generation

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Code Style Check (Spotless)
        run: ./gradlew spotlessCheck --no-daemon

      - name: Build Mod
        run: ./gradlew build --no-daemon

      - name: Upload Build Artifacts (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: opmod-build-${{ github.run_number }}
          path: build/libs/*.jar
          if-no-files-found: warn

  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate CHANGELOG.md (Conventional Commits)
        run: npx --yes conventional-changelog-cli -p conventionalcommits -r 0 -o CHANGELOG.md

      - name: Upload Changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md

      - name: Changelog Preview
        run: |
          echo "### CHANGELOG Preview" >> $GITHUB_STEP_SUMMARY
          head -n 40 CHANGELOG.md >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "*Full file attached as artifact.*" >> $GITHUB_STEP_SUMMARY